version: "3"

services:
  spike_api:
    container_name: spike_api
    build:
      context: "./"
      dockerfile: "Dockerfile"
    restart: always
    networks:
        - spike_network
    ports:
      - "8080:8080"

networks:
    spike_network: