use actix_web::web;

use crate::controllers::{
    self, address, mna, number, rsp, session, subscriber,
};

pub fn config_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(
        web::resource("/login").route(web::post().to_async(session::login)),
    )
    .service(
        web::resource("/logout").route(web::post().to_async(session::logout)),
    )
    .service(
        web::resource("/numbers")
            .route(web::get().to_async(number::list_numbers))
            .route(web::post().to_async(number::create_new_number)),
    )
    .service(
        web::resource("/numbers/{id}")
            .route(web::get().to_async(number::show_number))
            .route(web::put().to_async(number::update_number))
            .route(web::delete().to_async(controllers::dummy)),
    )
    .service(
        web::resource("/mna")
            .route(web::get().to_async(mna::list_mna))
            .route(web::post().to_async(mna::create_new_mna)),
    )
    .service(
        web::resource("/mna/{id}")
            .route(web::get().to_async(mna::show_mna))
            .route(web::put().to_async(mna::update_mna))
            .route(web::delete().to_async(controllers::dummy)),
    )
    .service(
        web::resource("/mna/{id}/numbers")
            .route(web::get().to_async(mna::show_numbers_per_mna)),
    )
    .service(
        web::resource("/rsp")
            .route(web::get().to_async(rsp::list_rsp))
            .route(web::post().to_async(rsp::create_new_rsp)),
    )
    .service(
        web::resource("/rsp/{id}")
            .route(web::get().to_async(rsp::show_rsp))
            .route(web::put().to_async(rsp::update_rsp))
            .route(web::delete().to_async(controllers::dummy)),
    )
    .service(
        web::resource("/rsp/{id}/subscribers")
            .route(web::get().to_async(controllers::dummy)),
    )
    .service(
        web::resource("/subscriber")
            .route(web::get().to_async(subscriber::list_subscribers))
            .route(web::post().to_async(subscriber::create_new_subscriber)),
    )
    .service(
        web::resource("/subscriber/{id}")
            .route(web::get().to_async(subscriber::show_subscriber))
            .route(web::put().to_async(subscriber::update_subscriber))
            .route(web::delete().to_async(controllers::dummy)),
    )
    .service(
        web::resource("/address")
            .route(web::get().to_async(address::list_addresses))
            .route(web::post().to_async(address::create_new_address)),
    )
    .service(
        web::resource("/address/{id}")
            .route(web::get().to_async(address::show_address))
            .route(web::put().to_async(address::update_address))
            .route(web::delete().to_async(controllers::dummy)),
    );
}
